// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: deals/messages/get.proto

import { Deal } from './common';

export const protobufPackage = 'deals';

export interface GetDealRequest {
  id: string;
}

export interface GetDealResponse {
  deal: Deal | undefined;
}

export const DEALS_PACKAGE_NAME = 'deals';
