// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: deals/messages/list.proto

import { Deal } from './common';

export const protobufPackage = 'deals';

export interface ListDealsRequest {
  page: number;
  pageSize: number;
}

export interface ListDealsResponse {
  deals: Deal[];
  totalCount: number;
}

export const DEALS_PACKAGE_NAME = 'deals';
