// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: notifications/messages/get.proto

import {
  NotificationMedium,
  NotificationStatus,
  NotificationType,
} from '../enums';
import { Notification } from './common';

export const protobufPackage = 'notifications';

export interface GetNotificationsRequest {
  userId: string;
  /** e.g., "unread", "read", "all" */
  status: NotificationStatus;
  /** e.g., "email", "sms", "push" */
  type: NotificationType;
  /** e.g., "email", "sms", " */
  medium: NotificationMedium;
  /** number of notifications to retrieve */
  limit: number;
  /** pagination offset */
  offset: number;
}

export interface GetNotificationsResponse {
  notifications: Notification[];
  /** total number of notifications for the user */
  total: number;
}

export const NOTIFICATIONS_PACKAGE_NAME = 'notifications';
