// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: deals/messages/common.proto

export const protobufPackage = 'deals';

export interface Deal {
  id: string;
  title: string;
  description: string;
  price: number;
  currency: string;
}

export const DEALS_PACKAGE_NAME = 'deals';
