// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: notifications/messages/common.proto

import { Timestamp } from '../../google/protobuf/timestamp';
import {
  NotificationMedium,
  NotificationStatus,
  NotificationType,
} from '../enums';

export const protobufPackage = 'notifications';

export interface Notification {
  id: string;
  userId: string;
  messageText?: string | undefined;
  /** e.g., "email", "sms", "push" */
  type: NotificationType;
  medium: NotificationMedium;
  status: NotificationStatus;
  /** Unix timestamp */
  timestamp: Timestamp | undefined;
}

export const NOTIFICATIONS_PACKAGE_NAME = 'notifications';
