// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: notifications/messages/send.proto

import { NotificationMedium, NotificationType } from '../enums';

export const protobufPackage = 'notifications';

export interface SendNotificationRequest {
  userId: string;
  message: string;
  type: NotificationType;
  /** e.g., "email", "sms", "push" */
  medium: NotificationMedium;
}

export interface SendNotificationResponse {
  success: boolean;
  message: string;
}

export const NOTIFICATIONS_PACKAGE_NAME = 'notifications';
