// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: notifications/enums.proto

export const protobufPackage = 'notifications';

export enum NotificationType {
  INFO = 0,
  WARNING = 1,
  ALERT = 2,
  PROMOTION = 3,
  UNRECOGNIZED = -1,
}

export enum NotificationMedium {
  EMAIL = 0,
  SMS = 1,
  PUSH = 2,
  IN_APP = 3,
  UNRECOGNIZED = -1,
}

export enum NotificationStatus {
  UNREAD = 0,
  READ = 1,
  ARCHIVED = 2,
  UNRECOGNIZED = -1,
}

export const NOTIFICATIONS_PACKAGE_NAME = 'notifications';
